### ISSUE TITLE
Verbetering [DO3]: Maak AttemptToMarks onderdeel van domein

### ISSUE THREAD

**Issue by arothuis-hu** [tmoerland/cisq1-lingo#3]
Hoewel je dit in een helperklasse kunt zetten, voelt het wat gek aan in een object-georiënteerde taal. Hoe dan ook: het gedrag om een attempt (String) om te zetten naar een lijst Marks is onderdeel van ofwel de Feedback ofwel het spelen van een ronde. Dat zijn domeinconcepten. 

Plaats deze helperklasse in het domein of maak deze functionaliteit onderdeel van de Feedback of Round klasse.

**Comment by tmoerland** [comment]
Functionaliteit van AttemptToMarks overgeheveld naar Feedback klasse (bae76ac2)
